name: drone3
version: "3.9"
networks:
  raft-shared:
    name: raft-shared
    driver: bridge
    external: true
services:
  drone:
    build:
      context: .
      dockerfile: drone/Dockerfile
    container_name: drone-3
    hostname: drone-3
    environment:
      DRONE_ID:         drone-3
      DRONE_HOST:       ${DRONE_HOST_IP:-drone-3}
      DRONE_RPC_PORT:   "7100"
      LAT_INICIAL:      ${LAT3_INICIAL:-26.55}
      LONG_INICIAL:     ${LONG3_INICIAL:-56.30}
      BROKER_ADDRS_RPC: "broker1:9010,broker2:9010,broker3:9010"
    ports:
      - "7103:7100"
    networks: [raft-shared]
    restart: unless-stopped
